# Generated by Django 3.2.13 on 2022-05-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='title',
            field=models.CharField(default='제목을 입력해주세요', max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='title',
            field=models.CharField(default='제목을 입력해주세요', max_length=200, verbose_name='제목'),
        ),
    ]
